import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { AuthProvider } from './context/AuthContext';
import App from './App';
import AppLayout from './components/layout/AppLayout';
import { getStore } from './services/store';

beforeEach(async()=>{(await getStore()).reset();window.history.replaceState({},'', '/');});
afterEach(()=>cleanup());
const renderAt=path=>{window.history.replaceState({},'',path);return render(<App/>)};

describe('React route and role rendering',()=>{
  it('redirects signed out root and allows login page',async()=>{renderAt('/');await waitFor(()=>expect(window.location.pathname).toBe('/login'));expect(screen.getByText('Đăng nhập không gian vận hành doanh nghiệp')).toBeTruthy();});
  it('authenticates an ACTIVE demo user and renders the protected shell',async()=>{renderAt('/login');fireEvent.change(screen.getByLabelText('Tên đăng nhập'),{target:{value:'nhanvien1'}});fireEvent.change(screen.getByLabelText('Mật khẩu'),{target:{value:'123'}});fireEvent.click(screen.getByRole('button',{name:'Đăng nhập'}));await waitFor(()=>expect(window.location.pathname).toBe('/agent'));expect((await screen.findAllByText('Trợ lý vận hành')).length).toBeGreaterThan(0);});
  it('shows only active seeded demo accounts and lets a row fill the login fields',async()=>{(await getStore()).logout();renderAt('/login');const username=await screen.findByText('nhanvien2 / 123');fireEvent.click(username.closest('button'));expect(screen.getByLabelText('Tên đăng nhập').value).toBe('nhanvien2');expect(screen.getByLabelText('Mật khẩu').value).toBe('123');});
  it('logs out through React routing and sends restricted HR URLs to organization',async()=>{const store=await getStore();store.login('nhanvien1','123');renderAt('/agent');fireEvent.click(await screen.findByRole('button',{name:'Đăng xuất'}));await waitFor(()=>expect(window.location.pathname).toBe('/login'));store.login('hr1','123');cleanup();renderAt('/procurement');await waitFor(()=>expect(window.location.pathname).toBe('/organization'));});
  it('keeps System Admin inside account and activity screens',async()=>{const store=await getStore();store.login('sysadmin1','123');renderAt('/agent');await waitFor(()=>expect(window.location.pathname).toBe('/organization'));expect(screen.getByText('Quản trị tài khoản')).toBeTruthy();expect(await screen.findByText('EMP015')).toBeTruthy();expect(screen.getByText('Cấp tài khoản')).toBeTruthy();});
  it('renders manager delegation and OPS access controls only in their workspaces',async()=>{const store=await getStore();store.login('quanly1','123');renderAt('/approvals');expect(await screen.findByText('Ủy quyền công việc')).toBeTruthy();cleanup();store.login('admin1','123');renderAt('/organization');expect((await screen.findAllByText('Cấu hình quyền')).length).toBeGreaterThan(0);expect(await screen.findByText('Ủy quyền công việc')).toBeTruthy();});
  it('grants a delegated approver the approval route from effective Store authority',async()=>{const store=await getStore();store.login('quanly1','123');const start=new Date().toISOString().slice(0,10);const end=new Date(Date.now()+86400000*5).toISOString().slice(0,10);store.createDelegation({from_user:'MGR001',to_user:'EMP001',permissions:['APPROVE_EXPENSE'],start_date:start,end_date:end});store.login('nhanvien2','123');renderAt('/approvals');expect(await screen.findByText('Hộp thư phê duyệt')).toBeTruthy();});
  it('renders every business route inside the authenticated shell for permitted roles',async()=>{const store=await getStore();for(const [account,paths] of [['nhanvien1',['/agent','/my-work','/procurement','/procurement/PR-001','/expenses','/expenses/EXP-001','/assets','/meetings','/forms','/policies','/catalogue']],['quanly1',['/agent','/my-work','/procurement','/expenses','/assets','/meetings','/forms','/policies','/approvals','/catalogue']],['hr1',['/organization','/forms','/policies']],['admin1',['/organization','/approvals','/activity']],['sysadmin1',['/organization','/activity']]]){store.reset();store.login(account,'123');for(const path of paths){cleanup();renderAt(path);await waitFor(()=>expect(screen.getByText('BUSINESS OPS')).toBeTruthy());await waitFor(()=>expect(screen.queryByText('Đang tải…')).toBeNull());expect(document.querySelector('.page-content')?.textContent).toBeTruthy();}}});
  it('keeps HR, manager, and system administration navigation role-aware',async()=>{const store=await getStore();store.login('hr1','123');const {unmount}=render(<MemoryRouter><AuthProvider><AppLayout/></AuthProvider></MemoryRouter>);await waitFor(()=>expect(screen.getByText('Tổ chức & phân quyền')).toBeTruthy());expect(screen.queryByText('Mua sắm')).toBeNull();expect(screen.queryByText('Phê duyệt')).toBeNull();unmount();store.login('quanly1','123');render(<MemoryRouter><AuthProvider><AppLayout/></AuthProvider></MemoryRouter>);await waitFor(()=>expect(screen.getByText('Phê duyệt')).toBeTruthy());expect(screen.queryByText('Tổ chức & phân quyền')).toBeNull();expect(screen.queryByText('Nhật ký hoạt động')).toBeNull();});
});
